import type { CatalogEntry } from "@/types/presentation";

/**
 * The slug is derived from the JSON filename — it's also the URL segment
 * used in /p/[slug]. Generated at build time and verified by the loader.
 */
function slugFromFile(file: string) {
  return file.replace(/^.*[\\/]/, "").replace(/\.json$/, "");
}

const ENTRIES: Omit<CatalogEntry, "slug">[] = [
  // ============= BEGINNER FUNDAMENTALS =============
  {
    file: "sample-presentation.json",
    title: "Introduction to Web Development",
    description: "Complete guide to modern web technologies from basics to advanced concepts",
    keywords: ["web", "html", "css", "javascript", "frontend", "backend", "fullstack"],
    category: ["frontend", "backend"],
    difficulty: "beginner",
  },
  {
    file: "advanced-slides.json",
    title: "Advanced Slide Components",
    description: "Testing Enhanced Features in BUDE Presentations",
    keywords: ["web", "html", "css", "javascript", "frontend", "backend", "fullstack"],
    category: ["frontend", "backend"],
    difficulty: "beginner",
  },
  {
    file: "tamil-movie-quiz.json",
    title: "Tamil Movie Challenge",
    description: "Hard-Level Post-2015 Movie Quizzes - Can You Guess Them All?",
    keywords: ["quiz", "tamil", "movies", "challenge", "fun"],
    category: ["movie", "games"],
    difficulty: "beginner",
  },
  {
    file: "ERPNext-Solutions-Catalog.json",
    title: "ERPNext Solutions Catalog",
    description: "Transforming Open-Source Flexibility into Enterprise-Grade Reliability",
    keywords: ["erpnext", "business", "enterprise", "solutions", "catalog"],
    category: ["business", "enterprise"],
    difficulty: "beginner",
  },
  {
    file: "intro-oss.json",
    title: "Introduction to Open Source",
    description: "Learn the fundamentals of open source software, from licensing to contributing",
    keywords: ["oss", "open source", "git", "github", "contribution"],
    category: ["devops"],
    difficulty: "beginner",
  },
  {
    file: "intro-git-github.json",
    title: "Introduction to Git & GitHub",
    description: "Complete version control mastery from zero to collaboration pro",
    keywords: ["git", "github", "version control", "vcs", "collaboration", "devops", "ci/cd", "open source"],
    category: ["devops"],
    difficulty: "beginner",
  },
  {
    file: "intro-linux.json",
    title: "Introduction to Linux",
    description: "Complete operating system guide from beginner to power user",
    keywords: ["linux", "ubuntu", "debian", "command-line", "bash", "sysadmin", "devops"],
    category: ["devops"],
    difficulty: "beginner",
  },
  {
    file: "intro-wsl.json",
    title: "Introduction to WSL (Windows Subsystem for Linux)",
    description: "Complete guide to Windows Subsystem for Linux from installation to advanced development workflows",
    keywords: ["wsl", "windows-subsystem-linux", "linux-on-windows", "development-environment", "docker-wsl", "wsl2", "windows-linux", "devops", "bash-on-windows"],
    category: ["devops", "tools"],
    difficulty: "beginner",
  },

  // ============= PROGRAMMING LANGUAGES =============
  {
    file: "intro-python.json",
    title: "Introduction to Python",
    description: "Complete Python guide from basics to advanced topics, OOP, and libraries",
    keywords: ["python", "programming", "code", "django", "flask", "data science"],
    category: ["programming"],
    difficulty: "beginner",
  },
  {
    file: "intro-ruby.json",
    title: "Ruby – Elegant, Expressive Programming Language",
    description: "A developer-friendly, expressive scripting language known for simplicity and productivity, widely used in web development through frameworks like Ruby on Rails.",
    keywords: ["ruby", "rails", "programming", "scripting", "web-development", "backend", "mvc", "oop", "productivity"],
    category: ["programming", "backend"],
    difficulty: "beginner",
  },
  {
    file: "intro-js.json",
    title: "JavaScript Fundamentals",
    description: "An Introduction to the Language of the Web",
    keywords: ["javascript", "js", "web development", "frontend", "es6"],
    category: ["programming", "frontend"],
    difficulty: "beginner",
  },
  {
    file: "intro-php.json",
    title: "PHP – Server-Side Web Development",
    description: "A foundational scripting language for dynamic web applications, powering platforms like WordPress, Laravel, and Drupal with vast ecosystem support.",
    keywords: ["php", "web-development", "backend", "laravel", "wordpress", "mysql", "server-side", "scripting", "mvc"],
    category: ["backend", "web-development"],
    difficulty: "beginner",
  },
  {
    file: "intro-dart.json",
    title: "Dart – Modern Programming Language for Apps",
    description: "Google's modern, object-oriented programming language optimized for UI, fast compilation, and cross-platform development — powering Flutter and beyond.",
    keywords: ["dart", "flutter", "programming", "oop", "async", "frontend", "backend", "mobile-development"],
    category: ["programming", "app-development"],
    difficulty: "intermediate",
  },
  {
    file: "intro-go.json",
    title: "Introduction to Go (Golang)",
    description: "Complete Go programming guide from basics to advanced concurrency features",
    keywords: ["go", "golang", "programming", "concurrency", "goroutines", "backend", "systems"],
    category: ["programming"],
    difficulty: "intermediate",
  },
  {
    file: "intro-bash.json",
    title: "Bash Scripting",
    description: "Professional shell scripting, process management, and POSIX compliance mastery.",
    keywords: ["bash", "shell", "scripting", "linux", "automation", "devops", "terminal"],
    category: ["programming", "devops"],
    difficulty: "intermediate",
  },
  {
    file: "intro-regex.json",
    title: "Regex Mastery",
    description: "Pattern matching excellence from basic tokens to backtracking optimization and PCRE.",
    keywords: ["regex", "regular-expressions", "patterns", "parsing", "automation"],
    category: ["programming", "tools"],
    difficulty: "intermediate",
  },
  {
    file: "intro-kotlin.json",
    title: "Kotlin – Modern Native Development",
    description: "Concise, safe, and interoperable language for Android, Multiplatform, and Backend development.",
    keywords: ["kotlin", "android", "jvm", "multiplatform", "coroutine", "programming"],
    category: ["programming", "app-development"],
    difficulty: "intermediate",
  },
  {
    file: "intro-swift.json",
    title: "Swift – Modern Apple Ecosystem Development",
    description: "Fast, safe, and interactive programming for iOS, macOS, watchOS, and beyond.",
    keywords: ["swift", "ios", "apple", "programming", "performance", "app-development"],
    category: ["programming", "app-development"],
    difficulty: "intermediate",
  },
  {
    file: "intro-csharp.json",
    title: "Introduction to C# Programming",
    description: "Modern, powerful, versatile language from basics to advanced concepts",
    keywords: ["csharp", "c#", "dotnet", "programming", "oop", "microsoft", "web", "desktop", "mobile"],
    category: ["programming"],
    difficulty: "intermediate",
  },
  {
    file: "intro-typescript.json",
    title: "TypeScript – Typed JavaScript for Scalable Applications",
    description: "Complete guide to TypeScript from basics to advanced patterns",
    keywords: ["typescript", "javascript", "types", "static-typing", "angular", "react", "nodejs"],
    category: ["programming"],
    difficulty: "intermediate",
  },
  {
    file: "intro-rust.json",
    title: "Rust – Systems Programming Language",
    description: "A memory-safe, high-performance systems programming language focused on safety, concurrency, and speed — ideal for backend services, embedded systems, and performance-critical software.",
    keywords: ["rust", "systems-programming", "memory-safety", "performance", "concurrency", "wasm", "cli", "backend", "safe-code"],
    category: ["programming", "backend"],
    difficulty: "advanced",
  },

  // ============= DATABASES =============
  {
    file: "intro-sql-databases.json",
    title: "SQL & Databases – Fundamentals of Relational Database Management",
    description: "Complete guide to relational databases and SQL from basics to advanced concepts",
    keywords: ["sql", "database", "rdbms", "mysql", "postgresql", "normalization", "acid", "joins"],
    category: ["database"],
    difficulty: "beginner",
  },
  {
    file: "intro-mysql.json",
    title: "Introduction to MySQL",
    description: "Complete database management guide from beginner to production ready",
    keywords: ["mysql", "database", "sql", "rdbms", "innodb", "replication", "backup"],
    category: ["database"],
    difficulty: "intermediate",
  },
  {
    file: "intro-postgresql.json",
    title: "Introduction to PostgreSQL",
    description: "Complete database management guide from beginner to advanced user",
    keywords: ["postgresql", "database", "sql", "rdbms", "jsonb", "acid", "backup", "performance", "indexing", "transactions"],
    category: ["database"],
    difficulty: "intermediate",
  },
  {
    file: "intro-mongodb.json",
    title: "Introduction to MongoDB",
    description: "Complete NoSQL database guide from beginner to production ready",
    keywords: ["mongodb", "nosql", "document", "database", "bson", "aggregation", "atlas"],
    category: ["database"],
    difficulty: "intermediate",
  },
  {
    file: "intro-redis.json",
    title: "Redis Masterclass",
    description: "High-performance in-memory systems, distributed patterns, and internals beyond simple caching.",
    keywords: ["redis", "nosql", "caching", "pubsub", "distributed-locking", "sentinel", "cluster"],
    category: ["database", "backend"],
    difficulty: "advanced",
  },
  {
    file: "intro-cassandra.json",
    title: "Cassandra & Distributed Systems",
    description: "Mastering write-optimized distributed databases, tunable consistency, and gossip protocols.",
    keywords: ["cassandra", "nosql", "distributed-systems", "cap-theorem", "scylladb", "big-data"],
    category: ["database"],
    difficulty: "advanced",
  },
  {
    file: "intro-elasticsearch.json",
    title: "Elasticsearch & Search Architecture",
    description: "Deep dive into Lucene internals, vector search, and horizontal search scaling.",
    keywords: ["elasticsearch", "lucene", "search-engine", "vector-search", "kibana", "elk-stack"],
    category: ["database", "backend"],
    difficulty: "advanced",
  },
  {
    file: "intro-neo4j.json",
    title: "Neo4j & Graph Data Modeling",
    description: "Exploring index-free adjacency, Cypher query optimization, and GDS algorithms.",
    keywords: ["neo4j", "graph-database", "cypher", "gds", "graph-theory", "knowledge-graphs"],
    category: ["database"],
    difficulty: "advanced",
  },
  {
    file: "intro-sqlite.json",
    title: "SQLite Mastery",
    description: "From embedded database basics to WAL mode, VFS, and advanced indexing internals.",
    keywords: ["sqlite", "database", "embedded", "sql", "performance", "acid"],
    category: ["database", "tools"],
    difficulty: "intermediate",
  },
  {
    file: "intro-supabase.json",
    title: "Supabase Masterclass",
    description: "The Open-Source Firebase Alternative: dedicated PostgreSQL, RLS policies, GoTrue Auth, Realtime Phoenix channels, storage buckets, and Edge Functions.",
    keywords: ["supabase", "postgresql", "baas", "auth", "realtime", "storage", "deno", "edge-functions", "vector-database", "rls"],
    category: ["database", "backend"],
    difficulty: "intermediate",
  },
  {
    file: "intro-firebase.json",
    title: "Firebase Masterclass",
    description: "Google's Mobile & Web Application Development Platform: Cloud Firestore, Realtime DB, Auth, Storage, Cloud Functions, Security Rules, and Emulator Suite.",
    keywords: ["firebase", "firestore", "nosql", "auth", "cloud-storage", "cloud-functions", "security-rules", "hosting", "fcm", "emulators"],
    category: ["database", "backend"],
    difficulty: "intermediate",
  },
  {
    file: "intro-prisma.json",
    title: "Prisma ORM Masterclass",
    description: "Next-Generation Type-Safe Database Access: schema.prisma declaration, data modeling, client CRUD APIs, migrations, N+1 query optimization, and serverless architectures.",
    keywords: ["prisma", "orm", "database", "typescript", "type-safety", "migrations", "postgresql", "mysql", "serverless", "accelerate"],
    category: ["database", "backend"],
    difficulty: "intermediate",
  },

  // ============= FRONTEND FRAMEWORKS =============
  {
    file: "bootstrap-presentation.json",
    title: "Introduction to Bootstrap",
    description: "Complete CSS framework guide from basics to advanced component development",
    keywords: ["bootstrap", "css", "frontend", "ui", "responsive", "components", "grid", "react", "vue", "angular"],
    category: ["frontend"],
    difficulty: "beginner",
  },
  {
    file: "tailwind-css-presentation.json",
    title: "Introduction to Tailwind CSS",
    description: "Complete utility-first CSS framework guide from basics to advanced component development",
    keywords: ["tailwind", "tailwindcss", "css", "frontend", "ui", "design", "responsive", "utility-first", "components", "react", "vue"],
    category: ["frontend"],
    difficulty: "beginner",
  },
  {
    file: "react-presentation.json",
    title: "Introduction to React",
    description: "Complete React.js guide from fundamentals to advanced hooks and state management",
    keywords: ["react", "reactjs", "javascript", "frontend", "hooks", "components", "jsx", "state", "props"],
    category: ["frontend"],
    difficulty: "intermediate",
  },
  {
    file: "intro-vue.json",
    title: "Introduction to Vue.js",
    description: "Progressive JavaScript framework - building user interfaces with ease",
    keywords: ["vue", "vuejs", "javascript", "frontend", "reactive", "components", "spa", "vite"],
    category: ["frontend"],
    difficulty: "beginner",
  },
  {
    file: "intro-svelte.json",
    title: "Introduction to Svelte",
    description: "Compile-time framework for cybernetically enhanced web apps",
    keywords: ["svelte", "sveltekit", "javascript", "frontend", "compiler", "reactive", "performance"],
    category: ["frontend"],
    difficulty: "beginner",
  },
  {
    file: "intro-angular.json",
    title: "Angular Masterclass",
    description: "Enterprise Frontend Web Development: Standalone component architecture, signals reactivity, RxJS pipelines, reactive forms, dependency injection, and SSR compilation.",
    keywords: ["angular", "typescript", "frontend", "spa", "signals", "rxjs", "google", "routing", "forms", "dependency-injection"],
    category: ["frontend"],
    difficulty: "intermediate",
  },
  {
    file: "nextjs-presentation.json",
    title: "Introduction to Next.js",
    description: "Complete full-stack React framework guide from basics to advanced App Router and deployment",
    keywords: ["nextjs", "react", "fullstack", "ssr", "ssg", "vercel", "app-router", "server-components"],
    category: ["frontend", "backend"],
    difficulty: "intermediate",
  },
  {
    file: "intro-maui.json",
    title: "Introduction to .NET MAUI",
    description: "Multi-platform App UI - one codebase for Android, iOS, Windows, and macOS",
    keywords: ["maui", "dotnet", "xamarin", "cross-platform", "mobile", "android", "ios", "windows", "macos"],
    category: ["frontend"],
    difficulty: "intermediate",
  },
  {
    file: "intro-flutter.json",
    title: "Flutter – Cross-Platform App Development",
    description: "Google's open-source framework for building high-performance, natively compiled mobile, web, and desktop applications from a single codebase using Dart.",
    keywords: ["flutter", "dart", "mobile-development", "cross-platform", "ui", "widgets", "android", "ios", "desktop", "web"],
    category: ["app-development", "frontend"],
    difficulty: "intermediate",
  },
  {
    file: "intro-ios-dev.json",
    title: "iOS Advanced Development",
    description: "Professional-grade iOS app development with SwiftUI and UIKit, covering modern architecture patterns, performance optimization, and framework integration.",
    keywords: ["ios", "swift", "swiftui", "uikit", "mobile-development", "xcode", "cocoapods", "app-development", "ios-architecture", "performance"],
    category: ["app-development", "frontend"],
    difficulty: "advanced",
  },
  {
    file: "intro-adminlte.json",
    title: "Introduction to AdminLTE",
    description: "Complete admin dashboard template guide from setup to advanced customization",
    keywords: ["adminlte", "bootstrap", "dashboard", "admin-template", "web-development", "ui-components", "laravel", "django", "react", "vue"],
    category: ["frontend", "tools"],
    difficulty: "intermediate",
  },

  // ============= BACKEND FRAMEWORKS & APIs =============
  {
    file: "nodejs-presentation.json",
    title: "Introduction to Node.js",
    description: "Complete server-side JavaScript runtime guide from basics to production deployment",
    keywords: ["nodejs", "javascript", "backend", "server", "express", "npm", "mongodb", "authentication", "api"],
    category: ["backend"],
    difficulty: "intermediate",
  },
  {
    file: "intro-expressjs.json",
    title: "Express.js Masterclass",
    description: "Deep dive from middleware internals to high-traffic enterprise architectures. Covers performance, security, and microservices.",
    keywords: ["express", "nodejs", "javascript", "api", "middleware", "routing", "rest", "backend", "web-framework", "performance", "security"],
    category: ["backend"],
    difficulty: "advanced",
  },
  {
    file: "intro-rest-api-swagger.json",
    title: "REST API & Swagger/OpenAPI",
    description: "Complete guide to REST API design principles and OpenAPI documentation",
    keywords: ["rest", "api", "swagger", "openapi", "http", "web-services", "api-design", "documentation", "aspnet-core", "nodejs", "spring-boot"],
    category: ["backend"],
    difficulty: "intermediate",
  },
  {
    file: "intro-spring-boot.json",
    title: "Spring Boot Architecture",
    description: "Enterprise-grade Java development with Spring Boot, Microservices, and Cloud-Native patterns.",
    keywords: ["spring-boot", "java", "microservices", "spring-cloud", "jpa", "security"],
    category: ["backend"],
    difficulty: "advanced",
  },
  {
    file: "intro-django.json",
    title: "Django Fundamentals",
    description: "Deep dive into the batteries-included Python framework, ORM optimization, and security hardening.",
    keywords: ["django", "python", "orm", "backend", "web-framework", "security"],
    category: ["backend"],
    difficulty: "advanced",
  },
  {
    file: "intro-nestjs-microservices.json",
    title: "NestJS & Microservices Proficiency",
    description: "Scalable Node.js architectures with TypeScript, gRPC, RabbitMQ, and Domain-Driven Design.",
    keywords: ["nestjs", "typescript", "microservices", "grpc", "rabbitmq", "ddd"],
    category: ["backend"],
    difficulty: "advanced",
  },
  {
    file: "intro-aspnet-core.json",
    title: "ASP.NET Core Architecture",
    description: "Building high-performance cross-platform APIs and microservices with .NET 8.",
    keywords: ["aspnet-core", "dotnet", "csharp", "api", "microservices", "entity-framework"],
    category: ["backend"],
    difficulty: "advanced",
  },
  {
    file: "intro-flask.json",
    title: "Flask Fundamentals",
    description: "Micro-framework mastery, extension ecosystems, and production deployment strategies.",
    keywords: ["flask", "python", "backend", "micro-framework", "api", "sqlalchemy"],
    category: ["backend"],
    difficulty: "intermediate",
  },
  {
    file: "intro-fastapi.json",
    title: "FastAPI Essentials",
    description: "Building modern, high-performance APIs with Python, Pydantic, and Asynchronous I/O.",
    keywords: ["fastapi", "python", "async", "pydantic", "api", "swagger"],
    category: ["backend"],
    difficulty: "intermediate",
  },
  {
    file: "intro-laravel.json",
    title: "Laravel 11 Mastery",
    description: "Eloquent ORM, Blade, and modern PHP ecosystem excellence.",
    keywords: ["laravel", "php", "backend", "mvc", "eloquent"],
    category: ["backend"],
    difficulty: "intermediate",
  },
  {
    file: "intro-laravel-inertia.json",
    title: "Laravel & Inertia.js Mastery",
    description: "Building classic SPAs without the complexity using Vue/React and Laravel.",
    keywords: ["laravel", "inertiajs", "vue", "react", "spa", "backend"],
    category: ["backend", "frontend"],
    difficulty: "advanced",
  },
  {
    file: "intro-nextjs-fastify.json",
    title: "Next.js 15 & Fastify Mastery",
    description: "High-performance full-stack React with the speed of Fastify.",
    keywords: ["nextjs", "fastify", "react", "backend", "performance"],
    category: ["backend", "frontend"],
    difficulty: "advanced",
  },
  {
    file: "intro-remix-express.json",
    title: "Remix & Express Mastery",
    description: "Modern web standards, loaders, and actions with Express.js.",
    keywords: ["remix", "express", "react", "web-standards", "backend"],
    category: ["backend", "frontend"],
    difficulty: "advanced",
  },
  {
    file: "intro-qwik-express.json",
    title: "Qwik & Express Mastery",
    description: "Resumability and instant-on apps with Qwik and Express.",
    keywords: ["qwik", "express", "resumability", "performance", "backend"],
    category: ["backend", "frontend"],
    difficulty: "advanced",
  },
  {
    file: "intro-solidstart-hono.json",
    title: "SolidStart & Hono Mastery",
    description: "Fine-grained reactivity with the speed of Hono.",
    keywords: ["solidstart", "hono", "solidjs", "reactivity", "backend"],
    category: ["backend", "frontend"],
    difficulty: "advanced",
  },
  {
    file: "intro-sveltekit-elysia.json",
    title: "SvelteKit & Elysia Mastery",
    description: "Type-safe, blazingly fast APIs with SvelteKit and Elysia.",
    keywords: ["sveltekit", "elysia", "svelte", "typescript", "backend"],
    category: ["backend", "frontend"],
    difficulty: "advanced",
  },
  {
    file: "intro-bun-hono.json",
    title: "Bun & Hono Mastery",
    description: "The next-generation runtime and the fastest web framework.",
    keywords: ["bun", "hono", "typescript", "runtime", "backend"],
    category: ["backend"],
    difficulty: "advanced",
  },
  {
    file: "intro-nuxt-nitro.json",
    title: "Nuxt 3 & Nitro Mastery",
    description: "The intuitive Vue framework with the power of Nitro.",
    keywords: ["nuxt", "nitro", "vue", "backend", "frontend"],
    category: ["backend", "frontend"],
    difficulty: "advanced",
  },
  {
    file: "intro-graphql.json",
    title: "GraphQL – API Query Language",
    description: "Complete guide to GraphQL API technology for efficient data fetching, real-time updates, and type-safe API development",
    keywords: ["graphql", "api", "query-language", "rest-alternative", "apollo", "hasura", "schema", "resolvers", "mutations", "subscriptions", "type-system", "graphiql", "react-graphql", "nodejs-graphql", "api-design", "data-fetching", "real-time", "websockets"],
    category: ["backend"],
    difficulty: "intermediate",
  },
  {
    file: "frappe-presentation.json",
    title: "Introduction to Frappe",
    description: "Full-stack web framework for rapid application development",
    keywords: ["frappe", "framework", "python", "erpnext", "web", "fullstack", "metadata"],
    category: ["backend", "business"],
    difficulty: "advanced",
  },
  {
    file: "intro-ionic.json",
    title: "Ionic – Hybrid Mobile App Development Framework",
    description: "A cross-platform mobile development framework built on web technologies, enabling developers to create iOS, Android, and web apps using HTML, CSS, and JavaScript with seamless integration into Angular, React, and Vue.",
    keywords: ["ionic", "mobile-development", "hybrid-apps", "capacitor", "angular", "react", "vue", "cross-platform", "javascript", "typescript"],
    category: ["mobile", "frontend", "cross-platform"],
    difficulty: "intermediate",
  },

  // ============= DEVOPS & INFRASTRUCTURE =============
  {
    file: "intro-devops-cicd.json",
    title: "DevOps & CI/CD Masterclass",
    description: "Accelerating Software Delivery from Commit to Production. A Practical Guide to Automation, Pipelines, Security, and Deployment Strategies.",
    keywords: ["devops", "ci/cd", "automation", "pipeline", "github-actions", "devsecops", "kubernetes", "docker", "gitops"],
    category: ["devops"],
    difficulty: "intermediate",
  },
  {
    file: "intro-docker.json",
    title: "Introduction to Docker & Containerization",
    description: "Complete containerization guide from beginner to production deployment",
    keywords: ["docker", "containers", "containerization", "devops", "microservices", "docker-compose", "kubernetes", "ci-cd"],
    category: ["devops"],
    difficulty: "intermediate",
  },
  {
    file: "intro-gitea.json",
    title: "Introduction to Gitea",
    description: "Lightweight, self-hosted Git service with complete control",
    keywords: ["gitea", "self-hosted", "git", "devops", "ci/cd", "docker", "kubernetes"],
    category: ["devops", "tools"],
    difficulty: "intermediate",
  },
  {
    file: "intro-kubernetes.json",
    title: "Kubernetes – Container Orchestration",
    description: "Production-grade platform for automating deployment, scaling, and management of containerized applications",
    keywords: ["kubernetes", "k8s", "container-orchestration", "docker", "cloud-native", "microservices", "devops", "cncf", "cka", "ckad"],
    category: ["devops"],
    difficulty: "advanced",
  },
  {
    file: "intro-terraform.json",
    title: "Terraform Deep Dive",
    description: "Infrastructure as Code - Learn to provision and manage cloud infrastructure with Terraform",
    keywords: ["terraform", "iac", "infrastructure", "devops", "cloud", "aws", "azure", "gcp", "hashicorp", "hcl"],
    category: ["devops", "cloud"],
    difficulty: "intermediate",
  },
  {
    file: "intro-aws.json",
    title: "Introduction to AWS Cloud",
    description: "Amazon Web Services fundamentals - cloud computing from basics to deployment",
    keywords: ["aws", "cloud", "ec2", "s3", "lambda", "rds", "devops", "infrastructure", "serverless"],
    category: ["devops"],
    difficulty: "beginner",
  },
  {
    file: "intro-system-design.json",
    title: "System Design Masterclass",
    description: "The definitive guide to designing and scaling massive distributed systems. Covers Load Balancing, Caching, Sharding, Microservices, and Case Studies (Netflix, Uber, Twitter).",
    keywords: ["system-design", "architecture", "scalability", "databases", "caching", "load-balancing", "microservices", "sharding", "consistent-hashing", "fault-tolerance", "observability", "case-studies"],
    category: ["backend", "devops"],
    difficulty: "advanced",
  },
  {
    file: "mqtt.json",
    title: "MQTT Masterclass: From IoT Fundamentals to AI-Enhanced Edge Computing",
    description: "Comprehensive 60+ slide guide covering MQTT fundamentals, advanced patterns, AI integration, and enterprise deployment",
    keywords: ["mqtt", "iot", "messaging", "pub-sub", "edge-computing", "broker", "qos", "security", "ai-iot"],
    category: ["backend", "devops", "iot"],
    difficulty: "advanced"
  },
  {
    file: "intro-google-home.json",
    title: "Introduction to Google Home & Smart Home Ecosystem",
    description: "Comprehensive guide to Google Home, Google Nest, smart home automation, and developer platforms including Matter & Thread",
    keywords: ["google home", "google nest", "smart home", "matter", "thread", "google assistant", "iot"],
    category: ["iot", "tools"],
    difficulty: "beginner"
  },

  // ============= BUSINESS & ENTERPRISE =============
  {
    file: "intro-metabase.json",
    title: "Introduction to Metabase",
    description: "Discover Metabase, an open source business intelligence and data visualization tool",
    keywords: ["metabase", "bi", "business intelligence", "data visualization", "analytics", "dashboards"],
    category: ["business", "ai-data"],
    difficulty: "intermediate",
  },
  {
    file: "erpnext-presentation.json",
    title: "Introduction to ERPNext",
    description: "World best open source ERP - complete business management solution",
    keywords: ["erpnext", "erp", "business", "management", "accounting", "inventory", "manufacturing", "open source"],
    category: ["business"],
    difficulty: "intermediate",
  },
  {
    file: "intro-frappe-product-suite.json",
    title: "Introduction to Frappe Product Suite",
    description: "Complete ecosystem of open source business applications including ERPNext, CRM, HR, and more built on Frappe Framework",
    keywords: ["frappe", "erpnext", "business", "enterprise", "open source", "erp", "crm", "hr", "accounting", "framework", "product suite", "business applications"],
    category: ["business"],
    difficulty: "advanced",
  },
  {
    file: "intro-grocy.json",
    title: "Introduction to Grocy - ERP for Home & Small Inventory Management",
    description: "Complete guide to Grocy open-source ERP system for household inventory, pantry management, and small business stock control",
    keywords: ["grocy", "erp", "inventory-management", "pantry-tracking", "self-hosted", "home-automation", "stock-management", "barcode-scanning", "meal-planning", "shopping-list", "chores", "maintenance-tracking", "docker", "raspberry-pi", "home-assistant", "rest-api", "automation", "open-source", "household-management", "small-business"],
    category: ["business", "tools"],
    difficulty: "intermediate",
  },
  {
    file: "intro-retool.json",
    title: "Introduction to Retool",
    description: "Low-code platform to build internal tools fast with pre-built components",
    keywords: ["retool", "low-code", "internal-tools", "admin-panel", "dashboard", "business", "rapid-development"],
    category: ["business"],
    difficulty: "intermediate",
  },
  {
    file: "intro-appsmith-tooljet.json",
    title: "Introduction to Appsmith & ToolJet",
    description: "Open-source low-code platforms for building internal tools and admin panels",
    keywords: ["appsmith", "tooljet", "low-code", "open-source", "internal-tools", "self-hosted", "business"],
    category: ["business"],
    difficulty: "beginner",
  },

  // ============= TOOLS & PRODUCTIVITY =============
  {
    file: "intro-powertoys.json",
    title: "Introduction to Microsoft PowerToys",
    description: "Complete Windows productivity toolkit guide from installation to advanced workflows",
    keywords: ["microsoft", "powertoys", "windows", "productivity", "utilities", "automation", "keyboard-shortcuts", "window-management", "fancyzones", "powertoys-run", "windows-tools", "power-user", "workflow-optimization"],
    category: ["tools"],
    difficulty: "beginner",
  },
  {
    file: "intro-ghost.json",
    title: "Ghost - Just a Blogging Platform",
    description: "Complete guide to modern publishing platform from setup to monetization",
    keywords: ["ghost", "blogging", "publishing", "nodejs", "cms", "membership", "newsletter", "headless-cms", "content-creation"],
    category: ["tools", "business"],
    difficulty: "intermediate",
  },
  {
    file: "intro-n8n.json",
    title: "Introduction to n8n",
    description: "Complete workflow automation platform guide from basics to advanced enterprise deployment",
    keywords: ["n8n", "workflow-automation", "node-based-automation", "self-hosted", "open-source", "fair-code", "api-integration", "webhooks", "automation-tools", "no-code", "low-code", "workflow-orchestration", "business-automation"],
    category: ["tools", "ai-data"],
    difficulty: "intermediate",
  },
  {
    file: "intro-stirling-pdf.json",
    title: "Introduction to Stirling PDF",
    description: "Complete self-hosted PDF processing toolkit with advanced document management capabilities",
    keywords: ["stirling-pdf", "pdf", "document-processing", "self-hosted", "open-source", "docker", "ocr", "pdf-manipulation", "document-management", "privacy", "pdf-tools", "self-hosted-pdf", "pdf-conversion", "pdf-editing"],
    category: ["tools"],
    difficulty: "intermediate",
  },
  {
    file: "intro-imhex.json",
    title: "Introduction to ImHex - Advanced Hex Editor",
    description: "Complete guide to ImHex hex editor for reverse engineering, firmware analysis, and binary forensics",
    keywords: ["imhex", "hex-editor", "reverse-engineering", "binary-analysis", "firmware", "malware-analysis", "forensics", "pattern-language", "security-research", "embedded-systems", "ghidra", "ida-pro", "radare2", "binary-patching", "memory-analysis", "file-formats", "elf", "pe", "png", "checksum", "hashing", "entropy-analysis", "data-visualization", "plugins", "scripting"],
    category: ["tools", "security"],
    difficulty: "advanced",
  },
  {
    file: "intro-keycloak.json",
    title: "Introduction to Keycloak",
    description: "Learn about Keycloak, an open source identity and access management solution",
    keywords: ["keycloak", "iam", "identity", "access management", "sso", "oauth2", "oidc"],
    category: ["security"],
    difficulty: "advanced",
  },
  {
    file: "antigravity-deep-dive.json",
    title: "Antigravity Deep Dive",
    description: "Redefining the Future of Collaborative Coding with Agentic AI",
    keywords: ["antigravity", "agentic-ai", "deepmind", "google", "automation", "pair-programming", "tools", "reasoning"],
    category: ["ai-data", "tools"],
    difficulty: "advanced",
  },

  {
    file: "intro-mcp.json",
    title: "Introduction to Model Context Protocol (MCP)",
    description: "Anthropic's open standard for AI tool integrations — architecture, primitives, transports, building servers, and the ecosystem.",
    keywords: ["mcp", "model-context-protocol", "anthropic", "llm", "ai", "tools", "agents", "json-rpc", "claude", "integration"],
    category: ["ai-data", "tools", "programming"],
    difficulty: "advanced",
  },
  // ============= EDUCATION & EXAMS =============
  {
    file: "bu-cet-rm-mock1.json",
    title: "Research Methodology - Mock 1 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Research Methodology.",
    keywords: ["phd", "entrance", "exam", "cet", "research-methodology", "rm", "education", "mock"],
    category: ["education", "research"],
    difficulty: "intermediate",
  },
  {
    file: "bu-cet-rm-mock2.json",
    title: "Research Methodology - Mock 2 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Research Methodology.",
    keywords: ["phd", "entrance", "exam", "cet", "research-methodology", "rm", "education", "mock"],
    category: ["education", "research"],
    difficulty: "intermediate",
  },
  {
    file: "bu-cet-rm-mock3.json",
    title: "Research Methodology - Mock 3 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Research Methodology.",
    keywords: ["phd", "entrance", "exam", "cet", "research-methodology", "rm", "education", "mock"],
    category: ["education", "research"],
    difficulty: "intermediate",
  },
  {
    file: "bu-cet-rm-mock4.json",
    title: "Research Methodology - Mock 4 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Research Methodology.",
    keywords: ["phd", "entrance", "exam", "cet", "research-methodology", "rm", "education", "mock"],
    category: ["education", "research"],
    difficulty: "intermediate",
  },
  {
    file: "bu-cet-rm-mock5.json",
    title: "Research Methodology - Mock 5 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Research Methodology.",
    keywords: ["phd", "entrance", "exam", "cet", "research-methodology", "rm", "education", "mock"],
    category: ["education", "research"],
    difficulty: "intermediate",
  },
  {
    file: "bu-cet-rm-mock6.json",
    title: "Research Methodology - Mock 6 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Research Methodology.",
    keywords: ["phd", "entrance", "exam", "cet", "research-methodology", "rm", "education", "mock"],
    category: ["education", "research"],
    difficulty: "intermediate",
  },
  {
    file: "bu-cet-rm-mock7.json",
    title: "Research Methodology - Mock 7 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Research Methodology.",
    keywords: ["phd", "entrance", "exam", "cet", "research-methodology", "rm", "education", "mock"],
    category: ["education", "research"],
    difficulty: "intermediate",
  },
  {
    file: "bu-cet-rm-mock8.json",
    title: "Research Methodology - Mock 8 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Research Methodology.",
    keywords: ["phd", "entrance", "exam", "cet", "research-methodology", "rm", "education", "mock"],
    category: ["education", "research"],
    difficulty: "intermediate",
  },
  {
    file: "bu-cet-rm-mock9.json",
    title: "Research Methodology - Mock 9 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Research Methodology.",
    keywords: ["phd", "entrance", "exam", "cet", "research-methodology", "rm", "education", "mock"],
    category: ["education", "research"],
    difficulty: "intermediate",
  },
  {
    file: "bu-cet-rm-mock10.json",
    title: "Research Methodology - Mock 10 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Research Methodology.",
    keywords: ["phd", "entrance", "exam", "cet", "research-methodology", "rm", "education", "mock"],
    category: ["education", "research"],
    difficulty: "intermediate",
  },
  {
    file: "bu-cet-cs-mock1.json",
    title: "Computer Science - Mock 1 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Computer Science & Applications.",
    keywords: ["phd", "entrance", "exam", "cet", "computer-science", "cs", "education", "mock"],
    category: ["education", "programming"],
    difficulty: "advanced",
  },
  {
    file: "bu-cet-cs-mock2.json",
    title: "Computer Science - Mock 2 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Computer Science & Applications.",
    keywords: ["phd", "entrance", "exam", "cet", "computer-science", "cs", "education", "mock"],
    category: ["education", "programming"],
    difficulty: "advanced",
  },
  {
    file: "bu-cet-cs-mock3.json",
    title: "Computer Science - Mock 3 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Computer Science & Applications.",
    keywords: ["phd", "entrance", "exam", "cet", "computer-science", "cs", "education", "mock"],
    category: ["education", "programming"],
    difficulty: "advanced",
  },
  {
    file: "bu-cet-cs-mock4.json",
    title: "Computer Science - Mock 4 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Computer Science & Applications.",
    keywords: ["phd", "entrance", "exam", "cet", "computer-science", "cs", "education", "mock"],
    category: ["education", "programming"],
    difficulty: "advanced",
  },
  {
    file: "bu-cet-cs-mock5.json",
    title: "Computer Science - Mock 5 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Computer Science & Applications.",
    keywords: ["phd", "entrance", "exam", "cet", "computer-science", "cs", "education", "mock"],
    category: ["education", "programming"],
    difficulty: "advanced",
  },
  {
    file: "bu-cet-cs-mock6.json",
    title: "Computer Science - Mock 6 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Computer Science & Applications.",
    keywords: ["phd", "entrance", "exam", "cet", "computer-science", "cs", "education", "mock"],
    category: ["education", "programming"],
    difficulty: "advanced",
  },
  {
    file: "bu-cet-cs-mock7.json",
    title: "Computer Science - Mock 7 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Computer Science & Applications.",
    keywords: ["phd", "entrance", "exam", "cet", "computer-science", "cs", "education", "mock"],
    category: ["education", "programming"],
    difficulty: "advanced",
  },
  {
    file: "bu-cet-cs-mock8.json",
    title: "Computer Science - Mock 8 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Computer Science & Applications.",
    keywords: ["phd", "entrance", "exam", "cet", "computer-science", "cs", "education", "mock"],
    category: ["education", "programming"],
    difficulty: "advanced",
  },
  {
    file: "bu-cet-cs-mock9.json",
    title: "Computer Science - Mock 9 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Computer Science & Applications.",
    keywords: ["phd", "entrance", "exam", "cet", "computer-science", "cs", "education", "mock"],
    category: ["education", "programming"],
    difficulty: "advanced",
  },
  {
    file: "bu-cet-cs-mock10.json",
    title: "Computer Science - Mock 10 (PhD CET)",
    description: "50 Multiple Choice Questions covering 5 topics for the PhD CET in Computer Science & Applications.",
    keywords: ["phd", "entrance", "exam", "cet", "computer-science", "cs", "education", "mock"],
    category: ["education", "programming"],
    difficulty: "advanced",
  },
  {
    file: "intro-linux-hardening.json",
    title: "Linux Hardening Masterclass",
    description: "Deep dive into Linux server security hardening. Covers SSH security, sysctl networking parameters, SELinux/AppArmor MAC policies, auditd monitoring, and namespace isolation.",
    keywords: ["security", "linux", "sysadmin", "hardening", "ssh", "selinux", "auditd", "firewall"],
    category: ["security", "devops"],
    difficulty: "advanced",
  },

  // ============= PERSONAL =============
  {
    file: "will-you-marry-me.json",
    title: "Will You Marry Me?",
    description: "A 27-slide proposal deck. For [Her Name]. With every ounce of feeling I have.",
    keywords: ["proposal", "marriage", "love", "for-her", "important", "personal"],
    category: ["personal"],
    difficulty: "beginner",
  },
];

export const CATALOG: CatalogEntry[] = ENTRIES.map((e) => ({
  ...e,
  slug: slugFromFile(e.file),
}));

export function findCatalogEntry(slug: string): CatalogEntry | undefined {
  return CATALOG.find((c) => c.slug === slug);
}
